apiVersion: v1
kind: Service
metadata:
  name: cicd-eks-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
spec:
  selector:
    app: cicd-eks-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000